Calculator UI
Addisu87/math-magicians pull request #2
Opened 2022-06-28 22:29 UTC by Addisu87

I have created a calculator user interface that displays all buttons and operators.

2022-06-28 23:30 UTC, Lameck1 commented on src/index.css
> +}
- [ ] This input field is not properly aligned. This is caused by the width properties given to it and also the one given to `.rowBtn`. We will talk about what to do with `.rowBtn` next.

  Let's fist remove the `max-width` and instead give it a `width: 100%`.

2022-06-28 23:32 UTC, Lameck1 commented on src/index.css
> +}
- [ ] Next, let's give the `.rowBtn` a width of 100% too. Using fixed widths is what's creating the problem.

2022-06-28 23:39 UTC, Lameck1 requested changes
Hi, @Addisu87, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Professional README ✔️
- Clean code ✔️ 
- Good commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**Please, remember to tag me in your question so I can receive the notification.**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 23:39 UTC, Lameck1 commented on src/index.css
> +}
- [ ] This input field is not properly aligned. This is caused by the width properties given to it and also the one is given to `.rowBtn`. We will talk about what to do with `.rowBtn` next.

  ![Screenshot 2022-06-29 021925](https://user-images.githubusercontent.com/45002654/176321618-18a32699-24a6-4073-9755-827e8be86f28.png)


  Let's fist remove the `max-width` and instead give it a `width: 100%`.

2022-06-28 23:39 UTC, Lameck1 commented on src/index.css
> +}
- [ ] Next, let's give the `.rowBtn` a width of 100% too. Using fixed widths is what's creating the problem.

2022-06-29 06:05 UTC, FrederickMih approved these changes
Hi @Addisu87 , 

![](https://media.giphy.com/media/z95UnKH3Rgdm1V9Y4f/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 06:57 UTC, merged